version: '2'
services:
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: adaptive_user
      MYSQL_PASSWORD: adaptive_pw
      MYSQL_DATABASE: adaptive_db
    volumes:
      - ./database/mysql:/var/lib/mysql
    restart: always
  graphql-api:
    build:
      context: ../graphql-api/.
    links:
      - db
    depends_on:
      - db
    environment:
      PORT: '3000'
    ports:
      - "3000:3000"
    volumes:
      - ../graphql-api/server.js:/app/server.js
      - ../graphql-api/config:/app/config
      - ../graphql-api/data:/app/data
      - ../graphql-api/migrations:/app/migrations
      - ../graphql-api/models:/app/models
    command: npm run start
  web:
    build:
      context: ../web-client/.
    links:
      - graphql-api
    depends_on:
      - graphql-api
    environment:
      PORT: '3000'
    ports:
      - "3001:3000"
    volumes:
      - ../web-client:/app
    command: npm run start
