version: '2'
services:
  graphql-db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: adaptive_user
      MYSQL_PASSWORD: adaptive_pw
      MYSQL_DATABASE: adaptive_db
    volumes:
      - ./database-graphql/mysql:/var/lib/mysql
    restart: always
  graphql-api:
    build:
      context: ../graphql-api/.
    links:
      - graphql-db
      - kafka-server
      - eeg-brainwave-api
    depends_on:
      - graphql-db
      - eeg-brainwave-api
      - kafka-server
    environment:
      DB_HOST: graphql-db
      DB_USERNAME: adaptive_user
      DB_PASSWORD: adaptive_pw
      DB_NAME: adaptive_db
      DB_PORT: 3306
      EEG_API: eeg-brainwave-api
      EEG_API_PORT: 8080
      API_PORT: 3000
      DEFAULT_LISTENER_COMMAND: hello
      KAFKA_SERVER: kafka-server
      KAFKA_PORT: 9092
      KAFKA_TOPIC: eeg
      KAFKA_DEBUG: "false"
    ports:
      - "3000:3000"
    volumes:
      - ../graphql-api/server.js:/app/server.js
      - ../graphql-api/config:/app/config
      - ../graphql-api/src:/app/src
      - ../graphql-api/migrations:/app/migrations
      - ../graphql-api/models:/app/models
      - ../graphql-api/node_modules
    command: npm run start
  eeg-db:
    image: mysql:5.6
    ports:
      - '3307:3307'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: adaptive_user
      MYSQL_PASSWORD: adaptive_pw
      MYSQL_DATABASE: adaptive_db
      MYSQL_TCP_PORT: 3307
      MYSQL_UNIX_PORT: 3307
    volumes:
      - ./database-eeg/mysql:/var/lib/mysql
    restart: always
  eeg-brainwave-api:
    build:
      context: ../eeg-brainwave-api/.
    links:
      - eeg-db
    depends_on:
      - eeg-db
    environment:
      DB_HOST: eeg-db
      DB_USERNAME: adaptive_user
      DB_PASSWORD: adaptive_pw
      DB_NAME: adaptive_db
      DB_PORT: 3307
      KAFKA_SERVER: kafka-server
      KAFKA_PORT: 9092
      KAFKA_TOPIC: eeg
      KAFKA_DEBUG: "false"
      MODELS_PATH: /resources/classifiers
      DATABASE_UTILS_PATH: /resources/DatabaseUtils.props
      DEBUG_SECRET: adaptive_system
    ports:
      - "8081:8080" # For debugging
    volumes:
      - ../eeg-brainwave-api/src/main/resources/DatabaseUtils.props:/resources/DatabaseUtils.props
      - ./classifiers:/resources/classifiers/
  web:
    build:
      context: ../web-client/.
    links:
      - graphql-api
    depends_on:
      - graphql-api
    environment:
      PORT: '3000'
    ports:
      - "3001:3000"
    volumes:
      - ../web-client:/app
      - ../web-client/node_modules
    command: npm run start
  zookeeper:
    image: confluentinc/cp-zookeeper:4.0.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka-server:
    image: confluentinc/cp-enterprise-kafka:4.0.1
    hostname: kafka-server
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-server:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  kafka-manager:
    container_name: kafka-manager
    image: thspinto/kafka-manager-docker
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: kafka-manager-secret
    depends_on:
      - kafka-server
